### ISSUE TITLE
Crash after Monal login and run in 30 seconds.

### ISSUE THREAD

**Issue by poormusic2001** [tmolitor-stud-tu/Monal#28]
### Description of my issue or feature request:
I removed the Monal which was in my phone before.

I use Xcode to build and run it.

Login with my jabbers.one account.

Then it crash after Monal run in 30 seconds.

It shows lastStanzaId is nil. The function is setLastStanzaId.

### The Monal version and system version I use:
4.8

### Additional information like screenshots:
<img width="1397" alt="截圖 2020-09-08 上午11 41 40" src="https://user-images.githubusercontent.com/10296589/92431094-28981f00-f1c9-11ea-8a1f-06e30af8753c.png">

---
[ ] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for regarding labels https://github.com/anurodhp/Monal/labels

**Comment by tmolitor-stud-tu** [comment]
Could you scroll up in the log to show the last received stanzas (the last "RECV:" line)?

**Comment by tmolitor-stud-tu** [comment]
Or send me the whole log per mail

**Comment by poormusic2001** [comment]
Sorry, I forget to keep the log, the crash can't be reproduced again.

Close the issue?

**Comment by poormusic2001** [comment]
I met again.
Send the log by mail.

**Comment by tmolitor-stud-tu** [comment]
I did not get the log, can you resend it?


Am Dienstag, 15. September 2020, 05:01:55 CEST schrieb JimTsai:
> I met again.
> Send the log by mail.

**Comment by poormusic2001** [comment]
Sent it again.

I sent to info@monal.im.

**Comment by tmolitor-stud-tu** [comment]
thanks, closing
