### ISSUE TITLE
Clicks “Account with Logs” Crash

### ISSUE THREAD

**Issue by poormusic2001** [tmolitor-stud-tu/Monal#37]
### Description of my issue or feature request:
I clicks "Settings"->"Chat Logs"->"Accounts with Logs" then the app crash.

### The Monal version and system version I use:
Testflight version 4.8(656)

### Additional information like screenshots:

---
[ ] I have cross-check this overview https://github.com/anurodhp/Monal/issues/322 as well es filtered for regarding labels https://github.com/anurodhp/Monal/labels

**Comment by poormusic2001** [comment]
I sent you logs by mail.

**Comment by tmolitor-stud-tu** [comment]
fixed in the next beta :)
