### ISSUE TITLE
Feature commits to version 4.9

### ISSUE THREAD

**Issue by Echolon** [tmolitor-stud-tu/Monal#42]
@tmolitor-stud-tu 

as requested:

- Notification Privacy Setting Options UI
- Complete parser rewrite (including a new project specific XML query language and abstractions for pubsub/pep, data forms and XMPP stanza elements)
- XEP-0172: Nicknames
- XEP-0084: User Avatar
- Actions to notifications
- Parse incoming data forms into XMPPDataForm
- Improve chat scrolling
- Many fixes, clean-up and improvements to for example pubsub (XEP-0060), OMEMO and UI
- /me command

Question: Is it possible in Github to somehow label these version commits? https://github.com/tmolitor-stud-tu/Monal/commit/b875b4c857e61956a544b9639ad53276602b9e3a

**Comment by tmolitor-stud-tu** [comment]
> Parse incoming data forms into XMPPDataForm
Thats a part of `XEP-0004 data forms abstraction layer`
I'm not sure if the data forms abstraction layer should be named at all.
Maybe summarize all of these internal changes as `Complete parser rewrite (including a new internal query language and abstractions for pubsub/pep, data forms and xmpp stanza elements)`

> Smacks revision 1.5.2
That's minimal, more or less internal and can be ignored for the changelog imho.

**Comment by Echolon** [comment]
Yep, did so

**Comment by tmolitor-stud-tu** [comment]
done, thanks: https://github.com/anurodhp/Monal/pull/506
